### ISSUE TITLE
REST APIの返却JSONがエスケープされている

### ISSUE THREAD

**Issue by joniburn** [TenteEEEE/quiche_pantie_patch#4]
![image](https://user-images.githubusercontent.com/1238086/62705708-e7af6300-ba28-11e9-9b7b-69125e6c6a06.png)
こんな感じで、ダブルクオートがエスケープされた文字列が返却されてしまっています。

`json.dumps()` が不要だと思うので外してみてください。
```diff
 class request_pantie_list(Resource):
     def get(self):
-        return json.dumps({"images": panties})
+        return {"images": panties}
```

**Comment by TenteEEEE** [comment]
フィードバックありがとうございました！
今後もなにか気づけば教えて下さいm(_ _)m
